version: 2

jobs:
  "environmentSetup":
   working_directory: ~/tmp
   docker:
    - image: circleci/openjdk:8-jdk
    - image: circleci/node:4.8.2
   steps:
    - checkout
    - run : echo "test pass"
    - run : npm install -g
    - run : npm test
    - run : echo "NPM installed successfully"
   
workflows:
 version: 2
 build:  
  jobs:
   - "environmentSetup"
